[package]
name = "mpv-client"
version = "0.1.0"
edition = "2021"

[lib]
name = "mpv_client"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
