[workspace]
members = [ "mpv-client-sys", "mpv-client" ]
resolver = "2"

[workspace.package]
readme = "README.md"
authors = ["Kevin Gavrois <kevin@gavrois.fr>"]
edition = "2021"
repository = "https://github.com/TheCactusVert/mpv-client"
license = "GPL-3.0"
keywords = ["mpv", "libmpv"]
